version: '3'
services:
  log:
    image: modsecurity_parser
    container_name: log
    environment:
      - LOG_PATH=audit.log
    volumes: 
      - ./db:/db
      - /var/log/apache2/modsec:/log

    
